/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quinta_Sys */

#ifndef _Included_com_quinta_Sys
#define _Included_com_quinta_Sys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_quinta_Sys
 * Method:    getInfo
 * Signature: (Lcom/quinta/Sistema;)V
 */
JNIEXPORT void JNICALL Java_com_quinta_Sys_getInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_quinta_Sys
 * Method:    getTime
 * Signature: (Lcom/quinta/Sistema;)V
 */
JNIEXPORT void JNICALL Java_com_quinta_Sys_getTime
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_quinta_Sys
 * Method:    getMb
 * Signature: (Lcom/quinta/Sistema;)V
 */
JNIEXPORT void JNICALL Java_com_quinta_Sys_getMb
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
